version: "3.9"

services:

  postgres:
    image: postgres:17
    container_name: oo_postgres

    environment:
      POSTGRES_DB: observability
      POSTGRES_USER: observability
      POSTGRES_PASSWORD: observability

      TZ: America/Sao_Paulo
      PGTZ: America/Sao_Paulo

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U observability -d observability"]
      interval: 5s
      timeout: 5s
      retries: 10


  redis:
    image: redis:8
    container_name: oo_redis

    ports:
      - "6380:6379"


  api:
    build: ./api

    container_name: oo_api

    ports:
      - "9000:8000"

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  frontend:
    image: nginx:alpine
    container_name: oo_frontend

    ports:
      - "8081:80"   # troque se essa porta estiver ocupada

    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api

volumes:
  postgres_data: